version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: nutrition_db
      POSTGRES_USER: nutrition_user
      POSTGRES_PASSWORD: nutrition_password
