# Generated by Django 4.2.1 on 2023-06-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_mealplan_patient_patientmealplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmealplan',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_mealplans', to='core.mealplan'),
        ),
    ]
