# Generated by Django 4.2.1 on 2023-06-07 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_patientmealplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mealplans', to=settings.AUTH_USER_MODEL),
        ),
    ]
