# Generated by Django 4.2.1 on 2023-06-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_patientmealplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmealplan',
            name='prescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.prescription'),
            preserve_default=False,
        ),
    ]
