# Generated by Django 4.2.1 on 2023-06-16 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_conversations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_diseases', models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('allergies', 'Allergies'), ('other', 'Other'), ('none', 'None')], max_length=100)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('moderate', 'Moderate'), ('active', 'Active')], max_length=20)),
                ('smoking_habits', models.CharField(choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular')], max_length=20)),
                ('alcohol_consumption', models.CharField(choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular')], max_length=20)),
                ('sleep_patterns', models.CharField(choices=[('less_than_6_hours', 'Less than 6 hours'), ('6_to_8_hours', '6 to 8 hours'), ('more_than_8_hours', 'More than 8 hours')], max_length=20)),
                ('current_diet', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('omnivorous', 'Omnivorous')], max_length=20)),
                ('food_allergies', models.CharField(choices=[('gluten', 'Gluten'), ('dairy', 'Dairy'), ('nuts', 'Nuts'), ('other', 'Other'), ('none', 'None')], max_length=100)),
                ('physical_disability', models.BooleanField(default=False)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
